version: 1.0.1.{build}
shallow_clone: true
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
nuget:
  account_feed: true
  disable_publish_on_pr: true
before_build:
  - cd src
  - nuget restore
  - cd ..
build:
  publish_nuget: true
  verbosity: minimal
test:
  assemblies: '*.Specs.dll'
deploy:
- provider: NuGet
  api_key:
    secure: hHPiLckcRQWeJe4L42auoJOxPIDRf5TVcaYv1oumZHbm6/qknPIm8+hHgPkwq9dY
